# config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm

  mappings:
    annonce_images:
      uri_prefix: /uploads/annonces
      upload_destination: '%kernel.project_dir%/public/uploads/annonces'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer  # <- optionnel (dÃ©-commente si tu veux des noms uniques)
      # delete_on_update: true   # <- options disponibles
      # delete_on_remove: true
      # inject_on_load: false
      # erase_fields: true
